#!/bin/sh

ASSETS_DIR="$(git config --get unity3d.assets-dir || echo "Assets")"
# Remove empty assets directory
find "$ASSETS_DIR" -depth -type d -empty -delete

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
git lfs post-merge "$@"